# Generated by Django 3.2.9 on 2021-12-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intexApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdprescriber',
            name='credentials',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
